console.log('undefined- ' + typeof(undefined));
console.log('-------------------');
console.log('5- ' + typeof(5));
console.log('-------------------');
console.log('Boolean- ' + typeof(true));
console.log('-------------------');
console.log('JavaScript- ' + typeof('str'));
console.log('-------------------');
console.log('{}- ' + typeof({}));
console.log('-------------------');
console.log('null- ' + typeof(null));
console.log('-------------------');
console.log('function(){}- ' + typeof(function(){}));